name: KiCad Export
run-name: KiCad Export 🚀
on:
  push:
    paths: ['hardware/**']

defaults:
  run:
    working-directory:
      ./hardware/roadster-charger/

jobs:
  KiCad-Export:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code  # needs to be first for working-directory to succeed
        uses: actions/checkout@v4

      - name: Install KiCad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-8.0-releases
          sudo apt update
          sudo apt install --install-recommends kicad

      - name: Create output directory
        run: mkdir output

      - name: Export schematic PDFs
        run: |
          mkdir -p output/schem-pdf
          for file in roadster-charger.kicad_sch; do kicad-cli sch export pdf --output output/schem-pdf/$(basename "$file" .kicad_sch).pdf "$file"; done

      - name: Export BOM
        run: |
          mkdir -p output/bom
          for file in *.kicad_sch; do kicad-cli sch export bom --fields "Reference,Value,Footprint,\${QUANTITY},\${DNP},MPN" --group-by "Reference,Value,Footprint,MPN" --format-preset CSV --output output/bom/$(basename "$file" .kicad_sch).csv "$file"; done

      - name: Export PCB PDFs
        run: |
          mkdir -p output/pcb-pdf
          for file in *.kicad_pcb; do kicad-cli pcb export pdf --layers F.Cu,In1.Cu,In2.Cu,B.Cu,B.SilkS,B.SilkS,Edge.Cuts --output output/pcb-pdf/$(basename "$file" .kicad_pcb).pdf "$file"; done
          for file in *.kicad_pcb; do kicad-cli pcb export pdf --layers F.Fab,B.Fab,Edge.Cuts --output output/pcb-pdf/$(basename "$file" .kicad_pcb)-fab.pdf "$file"; done

      - name: Export gerbers
        run: |
          mkdir -p output/gerbers
          kicad-cli pcb export gerbers --board-plot-params --output output/gerbers --precision 6 *.kicad_pcb

      # This task includes a trailing slash on the output directory due to a kicad-cli bug.
      - name: Export drill
        run: |
          mkdir -p output/gerbers
          kicad-cli pcb export drill *.kicad_pcb --format gerber --output output/gerbers/

      - name: Export component positions
        run: |
          mkdir -p output/pos
          kicad-cli pcb export pos --format csv --side both --units mm --output output/pos/pos.csv *.kicad_pcb

      - name: Export STEP
        run: |
          mkdir -p output/step
          for file in *.kicad_pcb; do kicad-cli pcb export step --subst-models --output output/step/$(basename "$file" .kicad_pcb).stp "$file"; done

      # This step does not respect working-directory
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hardware
          path: ./hardware/roadster-charger/output
